### ISSUE TITLE
Working directory always relative

### ISSUE THREAD

**Issue by FibreFoX** [bazaarvoice/maven-process-plugin#11]
Hi there,

first of all: thanks for your plugin, helped me to support CTRL-C and not aborting maven ;)

The bug:
https://github.com/bazaarvoice/maven-process-plugin/blob/master/src/main/java/com/bazaarvoice/maven/plugin/process/ProcessStartMojo.java#L51

It isn't possible to provide absolute path for working directory, I'll create a PR for this.

**Comment by fahdsiddiqui** [comment]
Thank you @FibreFoX - Checking your PR now.

**Comment by fahdsiddiqui** [comment]
Fixed in version 0.8 - https://github.com/bazaarvoice/maven-process-plugin/commit/105db704f752e7aa483a859c213fdeac69137b1d

**Comment by fahdsiddiqui** [comment]
https://github.com/bazaarvoice/maven-process-plugin/issues/11
