### ISSUE TITLE
stop process doesn't generate jacoco output file

### ISSUE THREAD

**Issue by ruiarodrigues** [bazaarvoice/maven-process-plugin#9]
I'm using the plugin to start a background process to run integration tests on it. The process is a java app. It's launched with the jacoco agent to have coverage data as follows:

```
<arguments>
     <argument>java</argument>
     <argument>-javaagent:org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=${basedir}/target/itjacoco.exec</argument>
     <argument>-jar</argument>
     <argument>${basedir}/target/dependency/im-javase.jar</argument>
</arguments>
```
Nevertheless the itjacoco.exec file is empty at the end of the maven run. The processes are killed but it seems that in a way the jacoco agent doesn't know and it doesn't dump the coverage data. If I do a Ctrl+C during the execution of the maven goals, the coverage data is performed.

**Comment by fahdsiddiqui** [comment]
@ruiarodrigues - make sure you have maven-failsafe-plugin configured in your pom. This will make sure that post-integration-test phase is always executed. Ctrl+C forces the code to run the stop logic, and so it seems to me that your build is breaking somewhere and exits without hitting the post-integration phase. Let me know if this helps. I will make sure that the readme reflects the use of maven-failsafe-plugin too.

**Comment by ruiarodrigues** [comment]
I'm already using the failsafe plugin as follows. Am I doing something wrong?
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-failsafe-plugin</artifactId>
	<version>2.18</version>
	<executions>
		<execution>
			<goals>
				<goal>integration-test</goal>
				<goal>verify</goal>
			</goals>
		</execution>
	</executions>
        <configuration>
       <parallel>none</parallel>
	<suiteXmlFiles>
		<suiteXmlFile>src/test/resources/SegmentsSuite.xml</suiteXmlFile>
	</suiteXmlFiles>
	</configuration>
</plugin>
```

**Comment by fahdsiddiqui** [comment]
That looks right to me. 
- Are all your tests passing?
- Also, can you confirm that you see the following at the end of the build output:
```bash
[INFO] --- process-exec-maven-plugin:0.7:stop-all (stop-shovel) @ quality ---
[INFO] Stopping all processes ...
[INFO] Stopping process: process-name
[INFO] Stopped process: process-name
```

**Comment by Niondir** [comment]
I struggle with as similar or the same problem. My jacoco.exec file is empty (doesn ot contain coverage data) when the process ended.

**Comment by ranjankumar03** [comment]
Same problem of empty .exec file getting generated.

**Comment by fahdsiddiqui** [comment]
Thanks @ranjankumar03 for commenting on your issue - https://github.com/bazaarvoice/maven-process-plugin/issues/10 . @Niondir and @ruiarodrigues - see @ranjankumar03 comments on the other issue about JBoss shut down issues being the cause of it.

**Comment by ranjankumar03** [comment]
I succeeded in generating jacaoco reports . Use shutdown command to kill jboss server.
